name: release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: bundle
        run: npx gulp bundle
      - name: release
#        env:
#          GITHUB_API_TOKEN: ${{ secrets.GITLAB_SYNC }}
#        run: npx gulp release
        uses: softprops/action-gh-release@v1
        with:
          files: build/ui-bundle.zip
